services:
  postgres:
    image: postgis/postgis:14-3.4
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=maps_db
    ports:
      - "5432:5432"
